{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "django-app.fullname" . }}-migrate-{{ .Values.color }}"
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
    color: {{ .Values.color }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "django-app.labels" . | nindent 8 }}
        color: {{ .Values.color }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "django-app.serviceAccountName" . }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: migrate
          image: "{{ .Values.migrate.image.repository | default .Values.image.repository }}:{{ .Values.migrate.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.migrate.image.pullPolicy | default .Values.image.pullPolicy }}
          command: ["python"]
          args: ["manage.py", "migrate", "--noinput"]

          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: "{{ .value }}"
              {{- end }}
              {{- if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}

            {{- if .Values.secretEnv }}
            {{- range $key, $value := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-app.fullname" $ }}-secret
                  key: {{ $key }}
            {{- end }}
            {{- end }}
{{- end }}