apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaosullivan/django-gitops
    targetRevision: main
    path: clusters/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
